"""
Deterministic query service for production demand forecasting intelligence.

This module is the authoritative analytics layer between the employee
question and the natural-language response layer.

Responsibilities
----------------
- Resolve medicines safely.
- Read only validated production forecasting artifacts.
- Return deterministic, JSON-safe structured facts.
- Retrieve forecast, uncertainty, model, routing, ranking, status,
  and overall summary information.
- Fail safely when required production data is unavailable or malformed.

No forecast values, model decisions, rankings, or routing evidence are
generated by this module. All factual outputs are derived directly from
the repository artifacts.
"""

from __future__ import annotations

import math
from typing import Any

import pandas as pd

from finemed_ai.forecast_intelligence.medicine_resolver import (
    MedicineResolver,
)
from finemed_ai.forecast_intelligence.repository import (
    ForecastRepository,
)


class ForecastQueryService:
    """
    Query interface over validated production forecasting artifacts.

    The service loads repository artifacts once during initialization and
    exposes deterministic methods for the conversational orchestration
    layer.
    """

    FORECAST_REQUIRED_COLUMNS = {
        "Medicine_ID",
        "Forecast_Date",
        "Predicted_Demand",
    }

    MEDICINE_REQUIRED_COLUMNS = {
        "MDCODE",
        "Product_Display_Name",
    }

    MAX_RANKING_LIMIT = 100

    def __init__(
        self,
        repository: ForecastRepository | None = None,
    ) -> None:
        self.repository = repository or ForecastRepository()

        (
            forecast,
            routing,
            medicines,
        ) = self.repository.load_all()

        self._forecast = self._prepare_forecast(
            forecast
        )

        self._routing = self._prepare_routing(
            routing
        )

        self._medicines = self._prepare_medicines(
            medicines
        )

        self._resolver = MedicineResolver(
            self._medicines
        )

    # ------------------------------------------------------------------
    # Medicine resolution
    # ------------------------------------------------------------------

    def resolve_medicine(
        self,
        query: str,
    ) -> dict[str, Any]:

        normalized_query = self._normalize_query(
            query
        )

        if not normalized_query:
            return {
                "query": "",
                "resolved": False,
                "medicine_id": None,
                "medicine_name": None,
                "match_type": None,
            }

        result = self._resolver.resolve(
            normalized_query
        )

        medicine_id = self._normalize_medicine_id(
            result.medicine_code
        )

        medicine_name = self._clean_string(
            result.medicine_name
        )

        resolved = bool(
            result.resolved
            and medicine_id
            and medicine_name
        )

        return {
            "query": self._clean_string(
                result.query
            )
            or normalized_query,
            "resolved": resolved,
            "medicine_id": medicine_id,
            "medicine_name": medicine_name,
            "match_type": self._clean_string(
                result.match_type
            ),
        }

    # ------------------------------------------------------------------
    # Forecast
    # ------------------------------------------------------------------

    def get_forecast(
        self,
        medicine_query: str,
    ) -> dict[str, Any]:

        medicine = self.resolve_medicine(
            medicine_query
        )

        if not medicine["resolved"]:
            return self._not_found_result(
                medicine_query
            )

        data = self._get_forecast_rows(
            medicine["medicine_id"]
        )

        if data.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_forecast_records_available",
            }

        data = self._valid_forecast_dates(
            data
        )

        if data.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_valid_forecast_dates_available",
            }

        predicted = self._numeric_series(
            data,
            "Predicted_Demand",
        )

        if predicted.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_valid_predicted_demand_available",
            }

        total_predicted = float(
            predicted.sum()
        )

        forecast_days = int(
            data["Forecast_Date"].nunique()
        )

        average_daily_demand = (
            total_predicted / forecast_days
            if forecast_days > 0
            else None
        )

        return {
            **medicine,
            "found": True,
            "forecast_start": self._date_to_iso(
                data["Forecast_Date"].min()
            ),
            "forecast_end": self._date_to_iso(
                data["Forecast_Date"].max()
            ),
            "forecast_days": forecast_days,
            "forecast_record_count": int(
                len(data)
            ),
            "total_predicted_demand": (
                self._safe_float(
                    total_predicted
                )
            ),
            "average_daily_demand": (
                self._safe_float(
                    average_daily_demand
                )
            ),
            "selected_model": (
                self._unique_value(
                    data,
                    "Selected_Model",
                )
            ),
            "eligibility_status": (
                self._unique_value(
                    data,
                    "Eligibility_Status",
                )
            ),
            "forecast_status": (
                self._unique_value(
                    data,
                    "Forecast_Status",
                )
            ),
        }

    # ------------------------------------------------------------------
    # Forecast uncertainty
    # ------------------------------------------------------------------

    def get_forecast_range(
        self,
        medicine_query: str,
    ) -> dict[str, Any]:

        medicine = self.resolve_medicine(
            medicine_query
        )

        if not medicine["resolved"]:
            return self._not_found_result(
                medicine_query
            )

        data = self._get_forecast_rows(
            medicine["medicine_id"]
        )

        if data.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_forecast_records_available",
            }

        data = self._valid_forecast_dates(
            data
        )

        if data.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_valid_forecast_dates_available",
            }

        forecast_days = int(
            data["Forecast_Date"].nunique()
        )

        p10 = self._quantile_summary(
            data,
            "P10",
            forecast_days,
        )

        p50 = self._quantile_summary(
            data,
            "P50",
            forecast_days,
        )

        p90 = self._quantile_summary(
            data,
            "P90",
            forecast_days,
        )

        return {
            **medicine,
            "found": True,
            "selected_model": (
                self._unique_value(
                    data,
                    "Selected_Model",
                )
            ),
            "forecast_start": self._date_to_iso(
                data["Forecast_Date"].min()
            ),
            "forecast_end": self._date_to_iso(
                data["Forecast_Date"].max()
            ),
            "forecast_days": forecast_days,
            "p10_available": p10["available"],
            "p50_available": p50["available"],
            "p90_available": p90["available"],
            "total_p10": p10["total"],
            "total_p50": p50["total"],
            "total_p90": p90["total"],
        }

    # ------------------------------------------------------------------
    # Model information
    # ------------------------------------------------------------------

    def get_model_info(
        self,
        medicine_query: str,
    ) -> dict[str, Any]:

        medicine = self.resolve_medicine(
            medicine_query
        )

        if not medicine["resolved"]:
            return self._not_found_result(
                medicine_query
            )

        routing = self._get_routing_rows(
            medicine["medicine_id"]
        )

        if routing.empty:
            return {
                **medicine,
                "found": False,
                "reason": "no_routing_record_available",
            }

        row = self._select_routing_row(
            routing
        )

        return {
            **medicine,
            "found": True,
            "selected_model": (
                self._value_or_none(
                    row,
                    "Selected_Model",
                )
            ),
            "chronos_absolute_error": (
                self._float_or_none(
                    row,
                    "Chronos_AE",
                )
            ),
            "tsb_absolute_error": (
                self._float_or_none(
                    row,
                    "TSB_AE",
                )
            ),
            "validation_windows": (
                self._int_or_none(
                    row,
                    "Validation_Windows",
                )
            ),
            "validation_advantage_pct": (
                self._float_or_none(
                    row,
                    "Validation_Advantage_Pct",
                )
            ),
            "routing_reason": (
                self._value_or_none(
                    row,
                    "Routing_Reason",
                )
            ),
        }

    # ------------------------------------------------------------------
    # Routing explanation
    # ------------------------------------------------------------------

    def get_routing_explanation(
        self,
        medicine_query: str,
    ) -> dict[str, Any]:

        model_info = self.get_model_info(
            medicine_query
        )

        if not model_info.get("found"):
            return model_info

        return {
            "query": model_info.get("query"),
            "resolved": model_info.get("resolved"),
            "medicine_id": model_info.get(
                "medicine_id"
            ),
            "medicine_name": model_info.get(
                "medicine_name"
            ),
            "found": True,
            "selected_model": model_info.get(
                "selected_model"
            ),
            "chronos_absolute_error": (
                model_info.get(
                    "chronos_absolute_error"
                )
            ),
            "tsb_absolute_error": (
                model_info.get(
                    "tsb_absolute_error"
                )
            ),
            "validation_windows": (
                model_info.get(
                    "validation_windows"
                )
            ),
            "validation_advantage_pct": (
                model_info.get(
                    "validation_advantage_pct"
                )
            ),
            "routing_reason": model_info.get(
                "routing_reason"
            ),
        }

    # ------------------------------------------------------------------
    # Ranking
    # ------------------------------------------------------------------

    def get_ranking(
        self,
        top_n: int = 10,
        ascending: bool = False,
    ) -> dict[str, Any]:

        limit = self._normalize_ranking_limit(
            top_n
        )

        if limit is None:
            raise ValueError(
                "top_n must be an integer between "
                f"1 and {self.MAX_RANKING_LIMIT}"
            )

        ranking_type = (
            "lowest_predicted_demand"
            if ascending
            else "highest_predicted_demand"
        )

        if self._forecast.empty:
            return {
                "found": False,
                "reason": "no_forecast_records_available",
                "ranking_type": ranking_type,
                "count": 0,
                "results": [],
            }

        data = self._valid_forecast_dates(
            self._forecast
        )

        if data.empty:
            return {
                "found": False,
                "reason": "no_valid_forecast_dates_available",
                "ranking_type": ranking_type,
                "count": 0,
                "results": [],
            }

        data = data.copy()

        data["Predicted_Demand"] = (
            pd.to_numeric(
                data["Predicted_Demand"],
                errors="coerce",
            )
        )

        data["Predicted_Demand"] = (
            data["Predicted_Demand"]
            .replace(
                [float("inf"), float("-inf")],
                pd.NA,
            )
        )

        data = data.dropna(
            subset=["Predicted_Demand"]
        )

        if data.empty:
            return {
                "found": False,
                "reason": (
                    "no_valid_predicted_demand_available"
                ),
                "ranking_type": ranking_type,
                "count": 0,
                "results": [],
            }

        grouped = (
            data.groupby(
                "Medicine_ID",
                as_index=False,
                dropna=True,
            )
            .agg(
                total_predicted_demand=(
                    "Predicted_Demand",
                    "sum",
                ),
                forecast_days=(
                    "Forecast_Date",
                    "nunique",
                ),
            )
        )

        grouped["Medicine_ID"] = (
            grouped["Medicine_ID"]
            .map(self._normalize_medicine_id)
        )

        grouped = grouped.dropna(
            subset=["Medicine_ID"]
        )

        medicine_lookup = (
            self._medicine_lookup_frame()
        )

        grouped = grouped.merge(
            medicine_lookup,
            how="left",
            on="Medicine_ID",
        )

        grouped["Medicine_Name"] = (
            grouped["Medicine_Name"]
            .fillna("UNKNOWN_MEDICINE")
        )

        grouped = grouped.sort_values(
            by=[
                "total_predicted_demand",
                "Medicine_ID",
            ],
            ascending=[
                ascending,
                True,
            ],
            kind="stable",
        ).head(limit)

        results: list[dict[str, Any]] = []

        for _, row in grouped.iterrows():
            results.append(
                {
                    "medicine_id": (
                        self._normalize_medicine_id(
                            row["Medicine_ID"]
                        )
                    ),
                    "medicine_name": (
                        self._clean_string(
                            row["Medicine_Name"]
                        )
                        or "UNKNOWN_MEDICINE"
                    ),
                    "total_predicted_demand": (
                        self._safe_float(
                            row[
                                "total_predicted_demand"
                            ]
                        )
                    ),
                    "forecast_days": (
                        self._safe_int(
                            row["forecast_days"]
                        )
                    ),
                }
            )

        return {
            "found": True,
            "ranking_type": ranking_type,
            "count": len(results),
            "results": results,
        }

    def get_top_demand(
        self,
        n: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Return the medicines with the highest total predicted demand.

        This compatibility method returns only the ranking results list,
        matching callers that expect list indexing.
        """

        ranking = self.get_ranking(
            top_n=n,
            ascending=False,
        )

        return ranking["results"]

    def get_lowest_demand(
        self,
        n: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Return the medicines with the lowest total predicted demand.
        """

        ranking = self.get_ranking(
            top_n=n,
            ascending=True,
        )

        return ranking["results"]

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------

    def get_status(
        self,
        status: str | None = None,
    ) -> dict[str, Any]:

        data = self._forecast.copy()

        if data.empty:
            return self._empty_status_result(
                status
            )

        normalized_status = self._normalize_status(
            status
        )

        if normalized_status:
            eligibility = self._string_column(
                data,
                "Eligibility_Status",
            )

            forecast_status = self._string_column(
                data,
                "Forecast_Status",
            )

            mask = (
                eligibility.eq(
                    normalized_status
                )
                | forecast_status.eq(
                    normalized_status
                )
            )

            data = data.loc[mask].copy()

        medicine_count = int(
            data["Medicine_ID"]
            .dropna()
            .map(self._normalize_medicine_id)
            .dropna()
            .nunique()
        )

        return {
            "found": True,
            "requested_status": normalized_status,
            "medicine_count": medicine_count,
            "record_count": int(len(data)),
            "eligibility_counts": (
                self._unique_medicine_counts(
                    data,
                    "Eligibility_Status",
                )
            ),
            "forecast_status_counts": (
                self._unique_medicine_counts(
                    data,
                    "Forecast_Status",
                )
            ),
        }

    # ------------------------------------------------------------------
    # Overall summary
    # ------------------------------------------------------------------

    def get_forecast_summary(
        self,
    ) -> dict[str, Any]:

        if self._forecast.empty:
            return self._empty_forecast_summary()

        data = self._valid_forecast_dates(
            self._forecast
        )

        if data.empty:
            return self._empty_forecast_summary()

        data = data.copy()

        data["Predicted_Demand"] = (
            pd.to_numeric(
                data["Predicted_Demand"],
                errors="coerce",
            )
        )

        data["Predicted_Demand"] = (
            data["Predicted_Demand"]
            .replace(
                [float("inf"), float("-inf")],
                pd.NA,
            )
        )

        data = data.dropna(
            subset=["Predicted_Demand"]
        )

        if data.empty:
            return self._empty_forecast_summary()

        total_predicted = float(
            data["Predicted_Demand"].sum()
        )

        medicine_count = int(
            data["Medicine_ID"]
            .dropna()
            .map(self._normalize_medicine_id)
            .dropna()
            .nunique()
        )

        forecast_record_count = int(
            len(data)
        )

        forecast_days = int(
            data["Forecast_Date"].nunique()
        )

        average_daily = (
            total_predicted / forecast_days
            if forecast_days > 0
            else None
        )

        average_per_medicine = (
            total_predicted / medicine_count
            if medicine_count > 0
            else None
        )

        average_per_record = (
            total_predicted / forecast_record_count
            if forecast_record_count > 0
            else None
        )

        return {
            "found": True,
            "medicine_count": medicine_count,
            "forecast_record_count": (
                forecast_record_count
            ),
            "forecast_start": self._date_to_iso(
                data["Forecast_Date"].min()
            ),
            "forecast_end": self._date_to_iso(
                data["Forecast_Date"].max()
            ),
            "forecast_days": forecast_days,
            "total_predicted_demand": (
                self._safe_float(
                    total_predicted
                )
                or 0.0
            ),
            "average_daily_predicted_demand": (
                self._safe_float(
                    average_daily
                )
            ),
            "average_predicted_demand_per_medicine": (
                self._safe_float(
                    average_per_medicine
                )
            ),
            "average_predicted_demand_per_record": (
                self._safe_float(
                    average_per_record
                )
            ),
            "model_distribution": (
                self._unique_medicine_counts(
                    data,
                    "Selected_Model",
                )
            ),
            "eligibility_distribution": (
                self._unique_medicine_counts(
                    data,
                    "Eligibility_Status",
                )
            ),
            "forecast_status_distribution": (
                self._unique_medicine_counts(
                    data,
                    "Forecast_Status",
                )
            ),
        }

    # ------------------------------------------------------------------
    # Artifact preparation
    # ------------------------------------------------------------------

    @classmethod
    def _prepare_forecast(
        cls,
        forecast: Any,
    ) -> pd.DataFrame:

        if not isinstance(
            forecast,
            pd.DataFrame,
        ):
            raise TypeError(
                "ForecastRepository.load_all() must return "
                "a pandas DataFrame for forecast data."
            )

        data = forecast.copy()

        if data.empty:
            return pd.DataFrame(columns=list(cls.FORECAST_REQUIRED_COLUMNS))

        cls._require_columns(
            data,
            cls.FORECAST_REQUIRED_COLUMNS,
            artifact_name="forecast",
        )


        data["Medicine_ID"] = (
            data["Medicine_ID"]
            .map(cls._normalize_medicine_id)
        )

        data = data.dropna(
            subset=["Medicine_ID"]
        )

        data["Forecast_Date"] = (
            pd.to_datetime(
                data["Forecast_Date"],
                errors="coerce",
            )
        )

        data["Predicted_Demand"] = (
            pd.to_numeric(
                data["Predicted_Demand"],
                errors="coerce",
            )
        )

        data["Predicted_Demand"] = (
            data["Predicted_Demand"]
            .replace(
                [float("inf"), float("-inf")],
                pd.NA,
            )
        )

        return data.reset_index(
            drop=True
        )

    @classmethod
    def _prepare_routing(
        cls,
        routing: Any,
    ) -> pd.DataFrame:

        if routing is None:
            return pd.DataFrame(
                columns=["Medicine_ID"]
            )

        if not isinstance(
            routing,
            pd.DataFrame,
        ):
            raise TypeError(
                "ForecastRepository.load_all() must return "
                "a pandas DataFrame for routing data."
            )

        data = routing.copy()

        if (
            not data.empty
            and "Medicine_ID"
            not in data.columns
        ):
            raise ValueError(
                "Routing artifact is missing required "
                "column: Medicine_ID"
            )

        if "Medicine_ID" not in data.columns:
            data["Medicine_ID"] = pd.Series(
                dtype="object"
            )

        data["Medicine_ID"] = (
            data["Medicine_ID"]
            .map(cls._normalize_medicine_id)
        )

        data = data.dropna(
            subset=["Medicine_ID"]
        )

        return data.reset_index(
            drop=True
        )

    @classmethod
    def _prepare_medicines(
        cls,
        medicines: Any,
    ) -> pd.DataFrame:

        if not isinstance(
            medicines,
            pd.DataFrame,
        ):
            raise TypeError(
                "ForecastRepository.load_all() must return "
                "a pandas DataFrame for medicine data."
            )

        data = medicines.copy()

        if data.empty:
            return pd.DataFrame(columns=list(cls.MEDICINE_REQUIRED_COLUMNS))

        cls._require_columns(
            data,
            cls.MEDICINE_REQUIRED_COLUMNS,
            artifact_name="medicine master",
        )


        data["MDCODE"] = (
            data["MDCODE"]
            .map(cls._normalize_medicine_id)
        )

        data["Product_Display_Name"] = (
            data["Product_Display_Name"]
            .map(cls._clean_string)
        )

        data = data.dropna(
            subset=[
                "MDCODE",
                "Product_Display_Name",
            ]
        )

        data = data.drop_duplicates(
            subset=["MDCODE"],
            keep="first",
        )

        return data.reset_index(
            drop=True
        )

    # ------------------------------------------------------------------
    # Internal data access
    # ------------------------------------------------------------------

    def _get_forecast_rows(
        self,
        medicine_id: str,
    ) -> pd.DataFrame:

        if self._forecast.empty:
            return self._forecast.copy()

        canonical_id = (
            self._normalize_medicine_id(
                medicine_id
            )
        )

        if not canonical_id:
            return self._forecast.iloc[0:0].copy()

        return self._forecast.loc[
            self._forecast["Medicine_ID"]
            == canonical_id
        ].copy()

    def _get_routing_rows(
        self,
        medicine_id: str,
    ) -> pd.DataFrame:

        if self._routing.empty:
            return self._routing.copy()

        canonical_id = (
            self._normalize_medicine_id(
                medicine_id
            )
        )

        if not canonical_id:
            return self._routing.iloc[0:0].copy()

        return self._routing.loc[
            self._routing["Medicine_ID"]
            == canonical_id
        ].copy()

    @staticmethod
    def _select_routing_row(
        routing: pd.DataFrame,
    ) -> pd.Series:

        return routing.iloc[0]

    @staticmethod
    def _valid_forecast_dates(
        data: pd.DataFrame,
    ) -> pd.DataFrame:

        if (
            data.empty
            or "Forecast_Date"
            not in data.columns
        ):
            return data.iloc[0:0].copy()

        result = data.copy()

        result["Forecast_Date"] = (
            pd.to_datetime(
                result["Forecast_Date"],
                errors="coerce",
            )
        )

        return (
            result.dropna(
                subset=["Forecast_Date"]
            )
            .sort_values(
                "Forecast_Date",
                kind="stable",
            )
        )

    # ------------------------------------------------------------------
    # Quantile helpers
    # ------------------------------------------------------------------

    @classmethod
    def _quantile_summary(
        cls,
        data: pd.DataFrame,
        column: str,
        forecast_days: int,
    ) -> dict[str, Any]:

        if (
            column not in data.columns
            or forecast_days <= 0
        ):
            return {
                "available": False,
                "total": None,
            }

        quantile_data = data[
            [
                "Forecast_Date",
                column,
            ]
        ].copy()

        quantile_data[column] = (
            pd.to_numeric(
                quantile_data[column],
                errors="coerce",
            )
        )

        quantile_data[column] = (
            quantile_data[column]
            .replace(
                [float("inf"), float("-inf")],
                pd.NA,
            )
        )

        valid = quantile_data.dropna(
            subset=[column]
        )

        if valid.empty:
            return {
                "available": False,
                "total": None,
            }

        valid_days = int(
            valid["Forecast_Date"].nunique()
        )

        if valid_days != forecast_days:
            return {
                "available": False,
                "total": None,
            }

        total = float(
            valid[column].sum()
        )

        return {
            "available": (
                cls._safe_float(total)
                is not None
            ),
            "total": cls._safe_float(
                total
            ),
        }

    # ------------------------------------------------------------------
    # Lookup helpers
    # ------------------------------------------------------------------

    def _medicine_lookup_frame(
        self,
    ) -> pd.DataFrame:

        if self._medicines.empty:
            return pd.DataFrame(
                columns=[
                    "Medicine_ID",
                    "Medicine_Name",
                ]
            )

        lookup = self._medicines[
            [
                "MDCODE",
                "Product_Display_Name",
            ]
        ].copy()

        lookup = lookup.rename(
            columns={
                "MDCODE": "Medicine_ID",
                "Product_Display_Name": (
                    "Medicine_Name"
                ),
            }
        )

        return lookup.drop_duplicates(
            subset=["Medicine_ID"],
            keep="first",
        )

    # ------------------------------------------------------------------
    # Status helpers
    # ------------------------------------------------------------------

    @classmethod
    def _string_column(
        cls,
        data: pd.DataFrame,
        column: str,
    ) -> pd.Series:

        if column not in data.columns:
            return pd.Series(
                "",
                index=data.index,
                dtype="object",
            )

        return (
            data[column]
            .map(cls._clean_string)
            .fillna("")
            .str.upper()
        )

    @classmethod
    def _unique_medicine_counts(
        cls,
        data: pd.DataFrame,
        category_column: str,
    ) -> dict[str, int]:

        if (
            data.empty
            or category_column
            not in data.columns
            or "Medicine_ID"
            not in data.columns
        ):
            return {}

        grouped = data[
            [
                "Medicine_ID",
                category_column,
            ]
        ].copy()

        grouped["Medicine_ID"] = (
            grouped["Medicine_ID"]
            .map(cls._normalize_medicine_id)
        )

        grouped[category_column] = (
            grouped[category_column]
            .map(cls._clean_string)
        )

        grouped = grouped.dropna(
            subset=[
                "Medicine_ID",
                category_column,
            ]
        )

        if grouped.empty:
            return {}

        counts = (
            grouped.groupby(
                category_column,
                dropna=True,
            )["Medicine_ID"]
            .nunique()
            .sort_index()
        )

        return {
            str(key): int(value)
            for key, value in counts.items()
        }

    def _empty_status_result(
        self,
        status: str | None,
    ) -> dict[str, Any]:

        return {
            "found": True,
            "requested_status": (
                self._normalize_status(
                    status
                )
            ),
            "medicine_count": 0,
            "record_count": 0,
            "eligibility_counts": {},
            "forecast_status_counts": {},
        }

    # ------------------------------------------------------------------
    # Validation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _require_columns(
        data: pd.DataFrame,
        required_columns: set[str],
        artifact_name: str,
    ) -> None:

        missing = sorted(
            required_columns
            - set(data.columns)
        )

        if missing:
            raise ValueError(
                f"{artifact_name.capitalize()} artifact "
                f"is missing required columns: "
                f"{', '.join(missing)}"
            )

    @classmethod
    def _normalize_query(
        cls,
        value: Any,
    ) -> str:

        if not isinstance(
            value,
            str,
        ):
            return ""

        return " ".join(
            value.strip().split()
        )

    @classmethod
    def _normalize_medicine_id(
        cls,
        value: Any,
    ) -> str | None:

        if value is None:
            return None

        try:
            if pd.isna(value):
                return None
        except TypeError:
            pass

        text = str(value).strip()

        if not text:
            return None

        if (
            text.endswith(".0")
            and text[:-2].isdigit()
        ):
            text = text[:-2]

        if text.isdigit():
            return text.zfill(4)

        return text

    @staticmethod
    def _normalize_ranking_limit(
        value: Any,
    ) -> int | None:

        if isinstance(
            value,
            bool,
        ):
            return None

        try:
            limit = int(value)
        except (
            TypeError,
            ValueError,
        ):
            return None

        if (
            limit < 1
            or limit
            > ForecastQueryService.MAX_RANKING_LIMIT
        ):
            return None

        return limit

    @staticmethod
    def _normalize_status(
        status: Any,
    ) -> str | None:

        if not isinstance(
            status,
            str,
        ):
            return None

        normalized = (
            " ".join(
                status.strip().split()
            )
            .upper()
        )

        return normalized or None

    # ------------------------------------------------------------------
    # Empty / failure contracts
    # ------------------------------------------------------------------

    @staticmethod
    def _not_found_result(
        query: str,
    ) -> dict[str, Any]:

        normalized_query = (
            ForecastQueryService._normalize_query(
                query
            )
        )

        return {
            "query": normalized_query,
            "resolved": False,
            "found": False,
            "medicine_id": None,
            "medicine_name": None,
            "match_type": None,
            "reason": "medicine_not_resolved",
        }

    @staticmethod
    def _empty_forecast_summary(
    ) -> dict[str, Any]:

        return {
            "found": True,
            "medicine_count": 0,
            "forecast_record_count": 0,
            "forecast_start": None,
            "forecast_end": None,
            "forecast_days": 0,
            "total_predicted_demand": 0.0,
            "average_daily_predicted_demand": None,
            "average_predicted_demand_per_medicine": None,
            "average_predicted_demand_per_record": None,
            "model_distribution": {},
            "eligibility_distribution": {},
            "forecast_status_distribution": {},
        }

    # ------------------------------------------------------------------
    # Value normalization
    # ------------------------------------------------------------------

    @staticmethod
    def _clean_string(
        value: Any,
    ) -> str | None:

        if value is None:
            return None

        try:
            if pd.isna(value):
                return None
        except TypeError:
            pass

        text = str(value).strip()

        return text or None

    @staticmethod
    def _safe_float(
        value: Any,
    ) -> float | None:

        if value is None:
            return None

        try:
            result = float(value)
        except (
            TypeError,
            ValueError,
        ):
            return None

        if not math.isfinite(result):
            return None

        return result

    @staticmethod
    def _safe_int(
        value: Any,
    ) -> int | None:

        if value is None:
            return None

        try:
            numeric = float(value)
        except (
            TypeError,
            ValueError,
        ):
            return None

        if not math.isfinite(numeric):
            return None

        return int(numeric)

    @staticmethod
    def _date_to_iso(
        value: Any,
    ) -> str | None:

        if value is None:
            return None

        try:
            if pd.isna(value):
                return None
        except TypeError:
            pass

        timestamp = pd.to_datetime(
            value,
            errors="coerce",
        )

        if pd.isna(timestamp):
            return None

        return timestamp.date().isoformat()

    @staticmethod
    def _numeric_series(
        data: pd.DataFrame,
        column: str,
    ) -> pd.Series:

        if (
            data.empty
            or column not in data.columns
        ):
            return pd.Series(
                dtype="float64"
            )

        values = pd.to_numeric(
            data[column],
            errors="coerce",
        )

        values = values.replace(
            [
                float("inf"),
                float("-inf"),
            ],
            pd.NA,
        )

        return values.dropna()

    @classmethod
    def _first_value(
        cls,
        data: pd.DataFrame,
        column: str,
    ) -> Any:

        if (
            data.empty
            or column not in data.columns
        ):
            return None

        values = data[column].dropna()

        if values.empty:
            return None

        value = values.iloc[0]

        if hasattr(
            value,
            "item",
        ):
            try:
                value = value.item()
            except ValueError:
                pass

        return cls._json_safe_value(
            value
        )

    @classmethod
    def _unique_value(
        cls,
        data: pd.DataFrame,
        column: str,
    ) -> Any:

        return cls._first_value(
            data,
            column,
        )

    @classmethod
    def _value_or_none(
        cls,
        row: pd.Series,
        column: str,
    ) -> Any:

        if column not in row.index:
            return None

        return cls._json_safe_value(
            row[column]
        )

    @classmethod
    def _float_or_none(
        cls,
        row: pd.Series,
        column: str,
    ) -> float | None:

        return cls._safe_float(
            cls._value_or_none(
                row,
                column,
            )
        )

    @classmethod
    def _int_or_none(
        cls,
        row: pd.Series,
        column: str,
    ) -> int | None:

        return cls._safe_int(
            cls._value_or_none(
                row,
                column,
            )
        )

    @staticmethod
    def _json_safe_value(
        value: Any,
    ) -> Any:

        if value is None:
            return None

        try:
            if pd.isna(value):
                return None
        except (
            TypeError,
            ValueError,
        ):
            pass

        if hasattr(
            value,
            "item",
        ):
            try:
                value = value.item()
            except (
                ValueError,
                AttributeError,
            ):
                pass

        if isinstance(
            value,
            float,
        ):
            return (
                value
                if math.isfinite(value)
                else None
            )

        return value